{% set name = "gtkmm" %}
{% set version = "3.24.6" %}
{% set ver_maj_min = ".".join(version.split(".")[:2]) %}
{% set abi_version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/gtkmm/{{ ver_maj_min }}/gtkmm-{{ version }}.tar.xz
  sha256: 4b3e142e944e1633bba008900605c341a93cfd755a7fa2a00b05d041341f11d6

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - gtkmm-{{ abi_version }} >={{ version }}

outputs:
  - name: gtkmm-{{ abi_version }}
    script: build_gtkmm.sh
    build:
      run_exports:
        - gtkmm-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - meson
        - ninja
        - pkg-config
        - {{ cdt('libice-devel') }}  # [linux]
        - {{ cdt('libsm-devel') }}  # [linux]
        - {{ cdt('libx11-devel') }}  # [linux]
        - {{ cdt('libxcomposite-devel') }}  # [linux]
        - {{ cdt('libxcursor-devel') }}  # [linux]
        - {{ cdt('libxdamage-devel') }}  # [linux]
        - {{ cdt('libxext-devel') }}  # [linux]
        - {{ cdt('libxi-devel') }}  # [linux]
        - {{ cdt('libxinerama-devel') }}  # [linux]
        - {{ cdt('libxfixes-devel') }}  # [linux]
        - {{ cdt('libxrandr-devel') }}  # [linux]
        - {{ cdt('libxrender-devel') }}  # [linux]
        - {{ cdt('libxtst-devel') }}  # [linux]
        - {{ cdt('mesa-libEGL-devel') }}  # [linux]
        - {{ cdt('mesa-libGL-devel') }}  # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
      host:
        - gtk3 >=3.24.0
        - cairomm-1.0
        - pangomm-1.4
        - sigcpp-2.0
        - atkmm-1.6
        - glibmm-2.4
        - glib
      run_constrained:
        - gtkmm {{ version }}
    test:
      requires:
        - pkg-config
      commands:
        - test -f ${PREFIX}/lib/libgtkmm-{{ abi_version }}${SHLIB_EXT}
        - pkg-config --cflags --libs gtkmm-{{ abi_version }}
        - pkg-config --exact-version {{ version }} gtkmm-{{ abi_version }}

  - name: gtkmm
    requirements:
      run:
        - gtkmm-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkgconfig/gtkmm-{{ abi_version }}.pc


about:
  home: https://www.gtkmm.org
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'C++ bindings for gtk'

extra:
  recipe-maintainers:
    - isuruf
